import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Script from "next/script";
import { Suspense } from "react";
import "./globals.css";
import { DevLinkProvider } from "@/devlink/DevLinkProvider";
import { QuizProvider } from "@/contexts/QuizContext";
import UTMTracker from "@/components/UTMTracker";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
      >
        {/* Ringba call tracking script */}
        <Script
          src="https://b-js.ringba.com/CAec88b51adf8b437d8e159c668629b896"
          strategy="afterInteractive"
        />
        {/* UTM tracking - captures and persists UTM parameters */}
        <Suspense fallback={null}>
          <UTMTracker />
        </Suspense>
        <QuizProvider>
          <DevLinkProvider>
            {/* Add here any Navbar or Header you want to be present on all pages */}
            {children}
            {/* Add here any Footer you want to be present on all pages */}
          </DevLinkProvider>
        </QuizProvider>
      </body>
    </html>
  );
}
